config/routes.rb
Rails.application.routes.draw do
  resources :temp_data
  resources :temp_devices
  get 'temp_device/dashboard', to: 'temp_devices#dashboard' , as:'dashboard_temp'
  get 'temp_device/update_grafico', to: 'temp_devices#update_grafico' , as:'update_grafico'
  
  resources :weight_devices
  get 'weight_device', to: 'weight_devices#dashboard', as: 'dashboard_weight'
  resources :weight_data
  resources :outlets
  devise_for :users
  get 'screens/show/',to: 'screens#configInit'
  get 'screens/show/:id',to: 'screens#show'
  get 'screens/update',to:'screens#update'
  get 'screens/index', to:'screens#index'
  get  'screens/modal/:id', to:'screens#open_modal',as:'open_modal'
  get  'screens/modalb/:id', to:'screens#open_modal_back',as:'open_modalb'
  post 'screens/modal/update',to:'screens#open_modal_update',as:'open_modal_update'
  post 'screens/modal/update',to:'screens#open_modalback_update',as:'open_modalback_update'
  get 'admin/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/outlet.rb
class Outlet < ApplicationRecord
end

app/models/screen.rb
class Screen < ApplicationRecord
    has_one_attached :background
    
end

app/models/temp_datum.rb
class TempDatum < ApplicationRecord
end

app/models/temp_device.rb
class TempDevice < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/weight_datum.rb
class WeightDatum < ApplicationRecord
end

app/models/weight_device.rb
class WeightDevice < ApplicationRecord
end

app/models/wialot_datum.rb
class WialotDatum < ApplicationRecord
end

app/models/wialot_device.rb
class WialotDevice < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
  def index
    @weight_devices = WeightDevice.all
    @outlets = Outlet.all
    @weight_data = WeightDatum.order('created_at DESC')
    @weight_data_1 = WeightDatum.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :access_user
  def index
    @weightDevice = WeightDevice.all()
  end

  private
  def access_user
    if user_signed_in?
      respond_to do |format|
        format.html { redirect_to '/admin/index/' }
      end
    end 
  end
end

app/controllers/outlets_controller.rb
class OutletsController < ApplicationController
  before_action :set_outlet, only: %i[ show edit update destroy ]

  # GET /outlets or /outlets.json
  def index
    @outlets = Outlet.all
  end

  # GET /outlets/1 or /outlets/1.json
  def show
  end

  # GET /outlets/new
  def new
    @outlet = Outlet.new
  end

  # GET /outlets/1/edit
  def edit
  end

  # POST /outlets or /outlets.json
  def create
    @outlet = Outlet.new(outlet_params)

    respond_to do |format|
      if @outlet.save
        format.html { redirect_to outlet_url(@outlet), notice: "Outlet was successfully created." }
        format.json { render :show, status: :created, location: @outlet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outlets/1 or /outlets/1.json
  def update
    respond_to do |format|
      if @outlet.update(outlet_params)
        format.html { redirect_to outlet_url(@outlet), notice: "Outlet was successfully updated." }
        format.json { render :show, status: :ok, location: @outlet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outlets/1 or /outlets/1.json
  def destroy
    @outlet.destroy

    respond_to do |format|
      format.html { redirect_to outlets_url, notice: "Outlet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outlet
      @outlet = Outlet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def outlet_params
      params.fetch(:outlet, {})
    end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  layout 'admin'
  def configInit
    ip = request.remote_ip 
    if Screen.find_by(ip:ip).present?
      ip = Screen.find_by(ip:ip)
      redirect_to "/screens/show/#{ip.screen_channel}"
    else
      if Screen.maximum("screen_channel") == nil
        screen = 1
        Screen.create(ip:ip,screen_channel:screen)
        Screen.find_by(ip:ip).present?
        ip = Screen.find_by(ip:ip)
        redirect_to "/screens/show/#{ip.screen_channel}"
      else
        screen = Screen.maximum("screen_channel")
        screen = screen + 1
        Screen.create(ip:ip,screen_channel:screen)
        Screen.find_by(ip:ip).present?
        ip = Screen.find_by(ip:ip)
        redirect_to "/screens/show/#{ip.screen_channel}"
      end
    end
  end

 def show
    @screen_id = params[:id]
    @info_outlet = Outlet.all
    @screenInfo = Screen.where(screen_channel:params[:id])
  end

  def update 
    # los canales son creados dependiendo de la cantidad de dispositivos
    # siempre vamos a tener 4 pantallas 
    # el broadcast debe ser dirigido por dispositivo, canal y pantallas
    screen_info = Screen.all
    screen_info.each do |screen| 
      out0 = Outlet.where(id_outlet_sz:screen.outlets_id_0)
      ActionCable.server.broadcast "screen_channel_#{screen.screen_channel}",
          {divPantalla:0,
          noutlet:out0[0].id_outlet_sz,
          nameoutlet:out0[0].outlet_name,
          desoutlet:out0[0].product_name,
          poutlet:out0[0].pack_name,
          toutlet:out0[0].pack_weight_kg}
      out1 = Outlet.where(id_outlet_sz:screen.outlets_id_1)
      ActionCable.server.broadcast "screen_channel_#{screen.screen_channel}",
          {divPantalla:1,
          noutlet:out1[0].id_outlet_sz,
          nameoutlet:out1[0].outlet_name,
          desoutlet:out1[0].product_name,
          poutlet:out1[0].pack_name,
          toutlet:out1[0].pack_weight_kg}
      out2 = Outlet.where(id_outlet_sz:screen.outlets_id_2)
      ActionCable.server.broadcast "screen_channel_#{screen.screen_channel}",
          {divPantalla:2,
          noutlet:out2[0].id_outlet_sz,
          nameoutlet:out2[0].outlet_name,
          desoutlet:out2[0].product_name,
          poutlet:out2[0].pack_name,
          toutlet:out2[0].pack_weight_kg}
      out3 = Outlet.where(id_outlet_sz:screen.outlets_id_3)
      ActionCable.server.broadcast "screen_channel_#{screen.screen_channel}",
          {divPantalla:3,
          noutlet:out3[0].id_outlet_sz,
          nameoutlet:out3[0].outlet_name,
          desoutlet:out3[0].product_name,
          poutlet:out3[0].pack_name,
          toutlet:out3[0].pack_weight_kg}
    end    
      respond_to do |format|
        format.html
        format.json { render json: {message:"update ready"} }
      end

    end

    def index
      @out = Outlet.all
      @devices = Screen.all
    end
  
    def open_modal
      @device = Screen.find(params[:id])
      respond_to do |format|
        format.js
      end
    
    end

    def open_modal_back
      @device = Screen.find(params[:id])
      respond_to do |format|
        format.js
      end
    end
  
    def open_modal_update
      @devices = Screen.all
      change_device = Screen.find(modal_params[:id])
      change_device.update(modal_params)
      ActionCable.server.broadcast "screen_channel_#{modal_params[:screen_channel]}",
      {refresh:1}
      ActionCable.server.broadcast "screen_channel_1000",
      {send_to_nodered:'screen_update_change'}
       respond_to do |format|
       format.js
       end
     end
    

    def modal_params
      params.require(:screen).permit(:id,:ip, :screen_channel, :cant_screen, :outlets_id_0, :outlets_id_1, :outlets_id_2, :outlets_id_3,:background)
    end
    
  end
    

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/outlets_helper.rb
module OutletsHelper
end

app/helpers/temp_data_helper.rb
module TempDataHelper
end

app/helpers/temp_devices_helper.rb
module TempDevicesHelper
end

app/helpers/weight_data_helper.rb
module WeightDataHelper
end

app/helpers/weight_devices_helper.rb
module WeightDevicesHelper
end

app/views/home/index.html.erb
<%= render 'shared/header' %>
  <%= render 'shared/headerHero' %>
    <main id="main">

      <!-- ======= App Features Section ======= -->
      <section id="features" class="features">
        <div class="container">

          <div class="section-title">
            <h2>Caracteristicas dispositivos</h2>
            <p>Nuestros dispositivos, permiten conectar sus equipos de medición mediante wifi, el dispositivo tiene la capacidad de enviar todas las mediciones que se generan en el proceso a la nube, todos los dispositivos estan interconectados entre sí y converguen en un mismo servidor, los datos estarán disponibles en tiempo real en un panel de control aportando total visibilidad del proceso debido a que estan conectados directamente a las Api de los calibradores. </p>
          </div>

          <div class="row no-gutters">
            <div class="col-xl-7 d-flex align-items-stretch order-2 order-lg-1">
              <div class="content d-flex flex-column justify-content-center">
                <div class="row">
                  <div class="col-md-6 icon-box" data-aos="fade-up">
                    <i class="bx bx-receipt"></i>
                    <h4>Control del Proceso</h4>
                    <p>En la plataforma podrás detectar desviaciones en el proceso en tiempo real.</p>
                  </div>
                  <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
                    <i class="bx bx-cube-alt"></i>
                    <h4>Reducción de Costos</h4>
                    <p>Mantener visibilizado el control de peso del proceso permite controlar a su vez las mermas y disminuir costos.</p>
                  </div>
                  <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
                    <i class="bx bx-images"></i>
                    <h4>Transformación Digital</h4>
                    <p>La automatización de los procesos de medición reduce la posibilidad errores humanos en digitación</p>
                  </div>
                  <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
                    <i class="bx bx-shield"></i>
                    <h4>Disponibilidad de la información</h4>
                    <p>El envio en tiempo real de la data permite la toma rápida de decisiones importantes. </p>
                  </div>
                  <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="400">
                    <i class="bx bx-atom"></i>
                    <h4>Gestión de la Calidad</h4>
                    <p>El registro de las mediciones que aseguran la calidad de los productos en tiempo real y sin manipulación humana, es un insumo ideal para mantener un estandar de aseguramiento de la calidad.</p>
                  </div>
                  <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="500">
                    <i class="bx bx-id-card"></i>
                    <h4>Escalabilidad</h4>
                    <p>Wialot se enfoca en automatizar todos los procesos de medición críticos de su proceso productivo, que realiza actualmente de forma manual, bajo el mismo principio de transformación digital, los procesos a controlar no tienen fin. </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="image col-xl-5 d-flex align-items-stretch justify-content-center order-1 order-lg-2"
              data-aos="fade-left" data-aos-delay="100">
              <%= image_tag 'features' ,class:'img-fluid' %>
            </div>
          </div>

        </div>
      </section><!-- End App Features Section -->

      <!-- ======= Details Section ======= -->
      <section id="details" class="details">
        <div class="container">
          <div class="row content">
            <div class="col-md-4" data-aos="fade-right">
              <%= image_tag 'details-1' ,class:'img-fluid' %>
            </div>
            <div class="col-md-8 pt-4" data-aos="fade-up">
              <h3>Beneficios</h3>
           
              <ul>
                <li><i class="bi bi-check"></i> Visibilidad de la información en tiempo real mediante conexión a internet.</li>
                <li><i class="bi bi-check"></i> Eliminación de trabajos manuales, errores humanos y perdida de información.</li>
                <li><i class="bi bi-check"></i> Eliminación de tiempos de respuesta en cuanto a resultados de analisis de datos.</li>
                <li><i class="bi bi-check"></i> Aseguramiento de la calidad y optimización de ganancias en la operación.</li>
                <li><i class="bi bi-check"></i> Respaldo de toda la información en la nube.</li>
                <li><i class="bi bi-check"></i> Soporte a nuestros clientes 24/7. </li>
              </ul>
              <p>
               Crear la infraestructura adecuada para pasar al siguiente nivel de la transformación digital es parte de nuestros servicios.
              </p>
            </div>
          </div>

        </div>
      </section><!-- End Details Section -->
      <!-- ======= Pricing Section ======= -->
      <!-- <section id="pricing" class="pricing">
        <div class="container">

          <div class="section-title">
            <h2>Precios</h2>
            <p>Conoce Te brindamos diversas modalidades de licenciamiento para acceder a nuestros productos y servicios. </p>
          </div>

          <div class="row no-gutters">
            <div class="col-lg-6 box featured" data-aos="fade-up">
              <h3>Saas</h3>
              <h4>A consultar<span>per month</span></h4>
              <ul>
                <li><i class="bx bx-check"></i> Quam adipiscing vitae proin</li>
                <li><i class="bx bx-check"></i> Nec feugiat nisl pretium</li>
                <li><i class="bx bx-check"></i> Nulla at volutpat diam uteera</li>
                <li><i class="bx bx-check"></i> Pharetra massa massa ultricies</li>
                <li><i class="bx bx-check"></i> Massa ultricies mi quis hendrerit</li>
              </ul>
              <a href="#" class="get-started-btn">Get Started</a>
            </div>

            <div class="col-lg-6 box" data-aos="fade-left">
              <h3>On-Premise</h3>
              <h4>A consultar<span>per month</span></h4>
              <ul>
                <li><i class="bx bx-check"></i> Quam adipiscing vitae proin</li>
                <li><i class="bx bx-check"></i> Nec feugiat nisl pretium</li>
                <li><i class="bx bx-check"></i> Nulla at volutpat diam uteera</li>
                <li><i class="bx bx-check"></i> Pharetra massa massa ultricies</li>
                <li><i class="bx bx-check"></i> Massa ultricies mi quis hendrerit</li>
              </ul>
              <a href="#" class="get-started-btn">Get Started</a>
            </div>

          </div>

        </div>
      </section>End Pricing Section -->
      <!-- ======= Contact Section ======= -->
      <section id="contact" class="contact">
        <div class="container" data-aos="fade-up">

          <div class="section-title">
            <h2>Contactanos</h2>
            <p>Para cualquier asesoria gratuita, ampliación de infomación, no dudes en contactarnos a traves de los siguientes canales: </p>
          </div>

          <div class="row">

            <div class="col-lg-6">
              <div class="row">
                <div class="col-lg-6 info">
                  <i class="bx bx-map"></i>
                  <h4>Dirección</h4>
                  <p>Calle Bombero Hugo Olguin 7160, Cerrillos RM Chile.</p>
                </div>
                <div class="col-lg-6 info">
                  <i class="bx bx-phone"></i>
                  <h4>Llamanos</h4>
                  <p>+56 9 5667 3437</p>
                </div>
                <div class="col-lg-6 info">
                  <i class="bx bx-envelope"></i>
                  <h4>Nuestro Email</h4>
                  <p>nestorurda@gmail.com</p>
                </div>
                <div class="col-lg-6 info">
                  <i class="bx bx-time-five"></i>
                  <h4>Horario Laboral</h4>
                  <p>Lun - Vie: 8AM to 6PM<br>Sábados: 9AM to 1PM</p>
                </div>
              </div>
            </div>

            <div class="col-lg-6">
              <form action="forms/contact.php" method="post" role="form" class="php-email-form" data-aos="fade-up">
                <div class="form-group">
                  <input placeholder="Tu Nombre" type="text" name="name" class="form-control" id="name" required>
                </div>
                <div class="form-group mt-3">
                  <input placeholder="Tu Email" type="email" class="form-control" name="email" id="email" required>
                </div>
                <div class="form-group mt-3">
                  <input placeholder="Asunto" type="text" class="form-control" name="Subject" id="subject" required>
                </div>
                <div class="form-group mt-3">
                  <textarea placeholder="Mensaje" class="form-control" name="Message" rows="5" required></textarea>
                </div>
                <div class="my-3">
                  <div class="loading">Loading</div>
                  <div class="error-message"></div>
                  <div class="sent-message">Tu mensaje ha sido enviado, Gracias!</div>
                </div>
                <div class="text-center"><button type="submit">Enviar Mensaje</button></div>
              </form>
            </div>

          </div>

        </div>
      </section><!-- End Contact Section -->

    </main><!-- End #main -->
    <%= render 'shared/footer' %>

app/views/screens/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Devices</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: open_modal_update_path,model:Screen, method: :post, local:false do |form| %>
            <%= form.hidden_field :id,value:@device.id %>
           <div class="field">
              <%= form.label 'Ip' %>
              <%= form.text_field :ip,value:@device.ip,class:'form-control' %>
           </div>
           <div class="field">
              <%= form.label 'Channel' %>
              <%= form.text_field :screen_channel,value:@device.screen_channel ,class:'form-control',disabled:true%>              
           </div>
           <div class="field">
              <%= form.label 'N° Screen' %>
              <%= form.select :cant_screen ,{'uno':1, 'dos':2, 'tres':3, 'cuatro':4},{include_blank: "- Selecciona cant pantallas -"},{ required: true,class:'form-control'}%>              
           </div>
           <div class="field">
              <%= form.label 'Config Out N° 0' %>
              <%= form.select :outlets_id_0,Outlet.all.map {|out| [ out.id_outlet_sz , out.id_outlet_sz]} ,{include_blank: "- Selecciona Salida Calibrador -"},class:'form-control'%> 
           </div>
           <div class="field">
              <%= form.label 'Config Out N° 1' %>
              <%= form.select :outlets_id_1,Outlet.all.map {|out| [ out.id_outlet_sz ,out.id_outlet_sz]} ,{include_blank: "- Selecciona Salida Calibrador -"},class:'form-control' %>
           </div>
           <div class="field">             
              <%= form.label 'Config Out N° 2' %>
              <%= form.select :outlets_id_2,Outlet.all.map {|out| [ out.id_outlet_sz , out.id_outlet_sz]} ,{include_blank: "- Selecciona Salida Calibrador -"},class:'form-control' %>
           </div>
           <div class="field">
              <%= form.label 'Config Out N° 3' %>
              <%= form.select :outlets_id_3,Outlet.all.map {|out| [ out.id_outlet_sz ,out.id_outlet_sz]} ,{include_blank: "- Selecciona Salida Calibrador -"},class:'form-control' %>  
           </div> 
           <div class="actions">
              <%= form.submit "Update", class:'btn btn-success mt-3' %>
           </div>           
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/screens/_modalback.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel1">Selecciona Fondo Pantalla</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: open_modalback_update_path, model:Screen, method: :post, local:false do |form| %>
            <%= form.hidden_field :id,value:@device.id %>
           <div>
    <%= form.file_field :background, class:'form-control' %>
  </div>
  <div>
    <%= form.submit "Guardar", class:'btn btn-primary mt-2' %>
  </div>           
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/screens/configInit.html.erb
<h1>Configurando</h1>
<%= @ip %>
<%= @message %>

app/views/screens/index.html.erb
<div class="container mt-5">
  <h2 class="pt-5">Dispositivos</h2>
  <table class="table text-center">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Ip</th>
        <th scope="col">Canal</th>
        <th scope="col">Nº Pantallas</th>
        <th scope="col">Salida #1</th>
        <th scope="col">Salida #2</th>
        <th scope="col">Salida #3</th>
        <th scope="col">Salida #4</th>

        <th scope="col">Acciones</th>
      </tr>
        </thead>
        <tbody id="data">
         <%= render 'shared_admin/screen' %>
        </tbody>
      </table>
      <h2>Salidas</h2>
      <table class="table text-center">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Sizer</th>
            <th scope="col">Nombre Salida</th>
            <th scope="col">Nombre Producto</th>
            <th scope="col">Nombre Display</th>
            <th scope="col">Nombre Empaque</th>
            <th scope="col">Peso Empaque KG</th>
            <th scope="col">FPM</th>
            <th scope="col">Estado</th>
          </tr>
            </thead>
            <tbody>
              <% @out.each_with_index do |o,idx| %>
              <tr>
                <th scope="row"><%= o.id %></th>
                <td><span id="id_outlet_sz-<%= idx %>"><%= o.id_outlet_sz %></span></td>
                <td><span id="outlet_name-<%= idx %>"><%= o.outlet_name %></span></td>
                <td><span id="product_name-<%= idx %>"><%= o.product_name %></span></td>
                <td><span id="product_display_name-<%= idx %>"><%= o.product_display_name %></span></td>
                <td><span id="pack_name-<%= idx %>"><%= o.pack_name %></span></td>
                <td><span id="pack_weight_kg-<%= idx %>"><%= o.pack_weight_kg %></span></td>
                <td><span id="outlet_fpm-<%= idx %>"><%= o.outlet_fpm %></span></td>
                <td><span id="outlet_status-<%= idx %>"><%= o.outlet_status %></span></td>   
              </tr>
              <% end %>          
            </tbody>
          </table>
      
    </div>
<div id="modal"></div>
<div id="modalback"></div>

    

app/views/screens/open_modal.js.erb
//populate modal
$('#modal').html('<%= escape_javascript(render(:partial => 'screens/modal')) %>');

//render modal
$('#exampleModal').modal('show');

app/views/screens/open_modal_back.js.erb
//populate modal
$('#modalback').html('<%= escape_javascript(render(:partial => 'screens/modalback')) %>');

//render modal
$('#exampleModal1').modal('show');

app/views/screens/open_modal_update.js.erb
$('.modal').modal('hide');
$('#data').html('<%= escape_javascript(render(:partial => 'shared_admin/screen',devices:@devices)) %>');