config/routes.rb
Rails.application.routes.draw do
  resources :temp_data
  resources :temp_devices
  get 'temp_device/dashboard', to: 'temp_devices#dashboard' , as:'dashboard_temp'
  get 'temp_device/update_grafico', to: 'temp_devices#update_grafico' , as:'update_grafico'
  
  resources :weight_devices
  get 'weight_device', to: 'weight_devices#dashboard', as: 'dashboard_weight'
  resources :weight_data
  resources :outlets
  devise_for :users
  get 'screens/show/',to: 'screens#configInit'
  get 'screens/show/:id',to: 'screens#show'
  get 'screens/update',to:'screens#update'
  get 'screens/index', to:'screens#index'
  get  'screens/modal/:id', to:'screens#open_modal',as:'open_modal'
  get  'screens/modalb/:id', to:'screens#open_modal_back',as:'open_modalb'
  post 'screens/modal/update',to:'screens#open_modal_update',as:'open_modal_update'
  post 'screens/modal/update',to:'screens#open_modalback_update',as:'open_modalback_update'
  get 'admin/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/outlet.rb
class Outlet < ApplicationRecord
end

app/controllers/outlets_controller.rb
class OutletsController < ApplicationController
  before_action :set_outlet, only: %i[ show edit update destroy ]

  # GET /outlets or /outlets.json
  def index
    @outlets = Outlet.all
  end

  # GET /outlets/1 or /outlets/1.json
  def show
  end

  # GET /outlets/new
  def new
    @outlet = Outlet.new
  end

  # GET /outlets/1/edit
  def edit
  end

  # POST /outlets or /outlets.json
  def create
    @outlet = Outlet.new(outlet_params)

    respond_to do |format|
      if @outlet.save
        format.html { redirect_to outlet_url(@outlet), notice: "Outlet was successfully created." }
        format.json { render :show, status: :created, location: @outlet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outlets/1 or /outlets/1.json
  def update
    respond_to do |format|
      if @outlet.update(outlet_params)
        format.html { redirect_to outlet_url(@outlet), notice: "Outlet was successfully updated." }
        format.json { render :show, status: :ok, location: @outlet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outlets/1 or /outlets/1.json
  def destroy
    @outlet.destroy

    respond_to do |format|
      format.html { redirect_to outlets_url, notice: "Outlet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outlet
      @outlet = Outlet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def outlet_params
      params.fetch(:outlet, {})
    end
end

app/helpers/outlets_helper.rb
module OutletsHelper
end

app/views/outlets/_form.html.erb
<%= form_with(model: outlet) do |form| %>
  <% if outlet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(outlet.errors.count, "error") %> prohibited this outlet from being saved:</h2>

      <ul>
        <% outlet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/outlets/edit.html.erb
<h1>Editing Outlet</h1>

<%= render 'form', outlet: @outlet %>

<%= link_to 'Show', @outlet %> |
<%= link_to 'Back', outlets_path %>

app/views/outlets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Outlets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @outlets.each do |outlet| %>
      <tr>
        <td><%= link_to 'Show', outlet %></td>
        <td><%= link_to 'Edit', edit_outlet_path(outlet) %></td>
        <td><%= link_to 'Destroy', outlet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Outlet', new_outlet_path %>

app/views/outlets/new.html.erb
<h1>New Outlet</h1>

<%= render 'form', outlet: @outlet %>

<%= link_to 'Back', outlets_path %>

app/views/outlets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_outlet_path(@outlet) %> |
<%= link_to 'Back', outlets_path %>