config/routes.rb
Rails.application.routes.draw do
  resources :temp_data
  resources :temp_devices
  get 'temp_device/dashboard', to: 'temp_devices#dashboard' , as:'dashboard_temp'
  get 'temp_device/update_grafico', to: 'temp_devices#update_grafico' , as:'update_grafico'
  
  resources :weight_devices
  get 'weight_device', to: 'weight_devices#dashboard', as: 'dashboard_weight'
  resources :weight_data
  resources :outlets
  devise_for :users
  get 'screens/show/',to: 'screens#configInit'
  get 'screens/show/:id',to: 'screens#show'
  get 'screens/update',to:'screens#update'
  get 'screens/index', to:'screens#index'
  get  'screens/modal/:id', to:'screens#open_modal',as:'open_modal'
  get  'screens/modalb/:id', to:'screens#open_modal_back',as:'open_modalb'
  post 'screens/modal/update',to:'screens#open_modal_update',as:'open_modal_update'
  post 'screens/modal/update',to:'screens#open_modalback_update',as:'open_modalback_update'
  get 'admin/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/outlet.rb
class Outlet < ApplicationRecord
end

app/models/screen.rb
class Screen < ApplicationRecord
    has_one_attached :background
    
end

app/models/temp_datum.rb
class TempDatum < ApplicationRecord
end

app/models/temp_device.rb
class TempDevice < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/weight_datum.rb
class WeightDatum < ApplicationRecord
end

app/models/weight_device.rb
class WeightDevice < ApplicationRecord
end

app/models/wialot_datum.rb
class WialotDatum < ApplicationRecord
end

app/models/wialot_device.rb
class WialotDevice < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
  def index
    @weight_devices = WeightDevice.all
    @outlets = Outlet.all
    @weight_data = WeightDatum.order('created_at DESC')
    @weight_data_1 = WeightDatum.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :access_user
  def index
    @weightDevice = WeightDevice.all()
  end

  private
  def access_user
    if user_signed_in?
      respond_to do |format|
        format.html { redirect_to '/admin/index/' }
      end
    end 
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/outlets_helper.rb
module OutletsHelper
end

app/helpers/temp_data_helper.rb
module TempDataHelper
end

app/helpers/temp_devices_helper.rb
module TempDevicesHelper
end

app/helpers/weight_data_helper.rb
module WeightDataHelper
end

app/helpers/weight_devices_helper.rb
module WeightDevicesHelper
end

app/views/admin/index.html.erb
<div class="container mt-5">
  Noticias y Alertas
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="es">

<head>
    <title>Wialot-adm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>   
   <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>    
   <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;700&display=swap" rel="stylesheet">
</head>

<body>
    <%= render('shared_admin/navbar') %>
    <div class="col d-flex flex-column h-sm-100">
        <main class="row overflow-auto">
            <div class="col">
                <%= yield %>
            </div>
        </main>
    </div>
    </div>
    </div>
    <script> 
    $(function () {
    $(".best_in_place").best_in_place();
    });
    
    
    </script>
    </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WialotApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>    

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <!-- Vendor CSS Files -->  
  <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
  </head>

  <body>
    
    <%= yield %> 
    
  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  <script>
  AOS.init();
  </script>
  </body>
</html>

app/views/shared/_footer.html.erb
<!-- ======= Footer ======= -->
  <footer id="footer">

    

    <div class="container py-4">
      <div class="copyright">
        &copy; Copyright <strong><span>Wialot</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-app-landing-page-template/ -->
        Designed by <a href="">Wialot</a>
      </div>
    </div>
  </footer><!-- End Footer -->

app/views/shared/_header.html.erb
 <!-- ======= Header ======= -->
  <header id="header" class="fixed-top  header-transparent ">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1>
        <!--<a href="index.html">Wialot</a></h1>-->
        <!-- Uncomment below if you prefer to use an image logo -->
        <a href="index.html"><%= image_tag 'logo',class:'img-fluid' %></a>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#features">Caracteristicas Dispositivos</a></li>
          <li><a class="nav-link scrollto" href="#pricing">Precio</a></li>
          <li><a class="nav-link scrollto" href="#contact">Contacto</a></li>
          <% if user_signed_in? %>
           <%= link_to "logout" , destroy_user_session_path, method: :delete, class:"dropdown-item" %>
          <% else %>
          <li><a class="getstarted" href="<%= new_user_session_path %>">logIn</a></li>
          <% end %>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

app/views/shared/_headerHero.html.erb
 <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container">
      <div class="row">
        <div class="col-lg-6 d-lg-flex flex-lg-column justify-content-center align-items-stretch pt-5 pt-lg-0 order-2 order-lg-1" data-aos="fade-up">
          <div>
            <h1>Dispositivos de Medición Inalámbricos</h1>
            <h2>La transformación digital de las empresas esta ocurriendo aquí y ahora, no permitas que tu empresa se quede atrapada en el pasado llenando registros en papel que no permiten medir, controlar y mucho menos mejorar tu negocio automatiza tu negocio con nuestra solución cloud. </h2>
            <div class="text-center">
              <a href="#" class="download-btn"><i class="bx bx-mail-send"></i>Conctáctanos</a>
              <a href="#" class="download-btn"><i class="bx bx-video"></i>Demo</a>
            </div>
          </div>
        </div>
        <div class="col-lg-6 d-lg-flex flex-lg-column align-items-stretch order-1 order-lg-2 hero-img" data-aos="fade-up">
          <%= image_tag 'hero-img-1',class:'img-fluid' %>
        </div>
      </div>
    </div>

  </section><!-- End Hero -->

app/views/shared_admin/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Devices</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: open_modal_update_path,model:Screen, method: :post, local:false do |form| %>
            <%= form.hidden_field :id,value:@device.id %>
           <div class="field">
              <%= form.label 'Ip' %>
              <%= form.text_field :ip,value:@device.ip,class:'form-control' %>
           </div>
           <div class="field">
              <%= form.label 'Channel' %>
              <%= form.text_field :screen_channel,value:@device.screen_channel ,class:'form-control'%>              
           </div>
           <div class="field">
              <%= form.label 'N° Screen' %>
              <%= form.text_field :cant_screen,value:@device.cant_screen ,class:'form-control'%>              
           </div>
           <div class="field">
              <%= form.label 'Config Out N° 0' %>
              <%= form.text_field :outlets_id_0,value:@device.outlets_id_0 ,class:'form-control'%> 
           </div>
           <div class="field">
              <%= form.label 'Config Out N° 1' %>
              <%= form.text_field :outlets_id_1,value:@device.outlets_id_1,class:'form-control' %>
           </div>
           <div class="field">             
              <%= form.label 'Config Out N° 2' %>
              <%= form.text_field :outlets_id_2,value:@device.outlets_id_2,class:'form-control' %>
           </div>
           <div class="field">
              <%= form.label 'Config Out N° 3' %>
              <%= form.text_field :outlets_id_3,value:@device.outlets_id_3,class:'form-control' %>  
           </div> 
           <div class="actions">
              <%= form.submit "Update", class:'btn btn-success mt-3' %>
           </div>           
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared_admin/_navbar.html.erb
<div class="container-fluid overflow-hidden">
    <div class="row vh-100 overflow-auto">
        <div class="ancho px-sm-2 px-0 bg-persona d-flex sticky-top">
            <div
                class="d-flex flex-sm-column flex-row flex-grow-1 align-items-center align-items-sm-start px-3 pt-2 text-white">
                <a href="/"
                    class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <a href="index.html"><%= image_tag 'logo',class:'img-fluid logo-admin' %></a>

                </a>
                <br>
                <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start"
                    id="menu">
                    <li>
                        <a href="<%= admin_index_path %>"  class="nav-link px-sm-0 px-2">
                            <i class='bx bx-coffee' ></i><span class="ms-1 d-none d-sm-inline">Noticias y Alertas</span>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="nav-link dropdown-toggle px-sm-0 px-1" id="dropdown"
                            data-bs-toggle="dropdown" aria-expanded="false">
                          <i class='bx bx-fullscreen'></i><span class="ms-1 d-none d-sm-inline">Pantallas</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdown">
                            <li><a class="dropdown-item" href="<%= screens_index_path %>">Lista de dispositivos</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="nav-link dropdown-toggle px-sm-0 px-1" id="dropdown"
                            data-bs-toggle="dropdown" aria-expanded="false">
                          <i class='bx bx-printer'></i><span class="ms-1 d-none d-sm-inline">Printer Server</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdown">
                            <li><a class="dropdown-item" href="<%= screens_index_path %>">Lista de dispositivos</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="nav-link dropdown-toggle px-sm-0 px-1" id="dropdown"
                            data-bs-toggle="dropdown" aria-expanded="false">
                           <i class='bx bx-reflect-horizontal'></i><span class="ms-1 d-none d-sm-inline">Balanzas</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdown">
                        
                            <li><a class="dropdown-item" href="<%= dashboard_weight_path %>">Dashboard</a></li>
                            <li><a class="dropdown-item" href="<%= weight_devices_path %>">Lista de dispositivos</a></li>
                            <li><a class="dropdown-item" href="<%= weight_data_path %>">Mediciones</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="nav-link dropdown-toggle px-sm-0 px-1" id="dropdown"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class='bx bxs-hot'></i><span class="ms-1 d-none d-sm-inline">Temperatura</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdown">
                        <li><a class="dropdown-item" href="<%= dashboard_temp_path %>">Dashboard</a></li>
                            <li><a class="dropdown-item" href="<%= temp_devices_path %>">Lista de dispositivos</a></li>
                            <li><a class="dropdown-item" href="<%= temp_data_path %>">Mediciones</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="nav-link dropdown-toggle px-sm-0 px-1" id="dropdown"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class='bx bx-water'></i><span class="ms-1 d-none d-sm-inline">Humedad</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdown">
                        <li><a class="dropdown-item" href="<%= admin_index_path %>">Dashboard</a></li>
                            <li><a class="dropdown-item" href="">Lista de dispositivos</a></li>
                            <li><a class="dropdown-item" href="">Mediciones</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="nav-link dropdown-toggle px-sm-0 px-1" id="dropdown"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class='bx bx-sort-alt-2'></i><span class="ms-1 d-none d-sm-inline">Nivel</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdown">
                        <li><a class="dropdown-item" href="<%= admin_index_path %>">Dashboard</a></li>
                            <li><a class="dropdown-item" href="">Lista de dispositivos</a></li>
                            <li><a class="dropdown-item" href="">Mediciones</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="nav-link dropdown-toggle px-sm-0 px-1" id="dropdown"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class='bx bx-equalizer'></i><span class="ms-1 d-none d-sm-inline">Flujo</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdown">
                        <li><a class="dropdown-item" href="<%= admin_index_path %>">Dashboard</a></li>
                            <li><a class="dropdown-item" href="">Lista de dispositivos</a></li>
                            <li><a class="dropdown-item" href="">Mediciones</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="nav-link dropdown-toggle px-sm-0 px-1" id="dropdown"
                            data-bs-toggle="dropdown" aria-expanded="false">
                           <i class='bx bxl-deezer'></i><span class="ms-1 d-none d-sm-inline">Configuraciones</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdown">
                            <li><a class="dropdown-item" href="">Todos los pedidos</a></li>
                            <li><a class="dropdown-item" href="#">Pedidos Abandonados</a></li>
                            <li><a class="dropdown-item" href="#">Despachos</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="">Seguimiento Pedido</a></li>
                        </ul>
                    </li>
                    
                </ul>
                <div class="py-sm-4 mt-sm-auto ms-auto ms-sm-0 flex-shrink-1">
                <%= link_to "Logout", destroy_user_session_path, :method => :delete, class:'getboton' %>
                </div>
            </div>
        </div>

app/views/shared_admin/_screen.html.erb
 <% @devices.each do |s| %>
          <tr>
            <th scope="row"><%= s.id %></th>
            <td><%= s.ip %></td>
            <td><%= s.screen_channel %></td>
            <td><%= s.cant_screen %></td>
            <td><%= s.outlets_id_0 %></td>
            <td><%= s.outlets_id_1 %></td>
            <td><%= s.outlets_id_2 %></td>
            <td><%= s.outlets_id_3 %></td>      
            <td><%= link_to "", open_modalb_path(s.id),class:'btn btn-sm bx bx-screenshot',type:'button','data-bs-toggle':"tooltip", 'data-bs-placement':"left", title:'Cambiar fondo', remote: true %>
            <%= link_to "", open_modal_path(s.id),class:'btn btn-sm  bx bxs-color',type:'button','data-bs-toggle':"tooltip", 'data-bs-placement':"left", title:'Cambiar Parametros', remote: true %>
            <a type="button" data-bs-toggle="tooltip" data-bs-placement="left" title="Ir a la Pantalla" class="btn btn-sm  bx bxs-right-top-arrow-circle"href="/screens/show/<%= s.screen_channel %>"></a></td>
          </tr>
 <% end  %>