config/routes.rb
Rails.application.routes.draw do
  resources :temp_data
  resources :temp_devices
  get 'temp_device/dashboard', to: 'temp_devices#dashboard' , as:'dashboard_temp'
  get 'temp_device/update_grafico', to: 'temp_devices#update_grafico' , as:'update_grafico'
  
  resources :weight_devices
  get 'weight_device', to: 'weight_devices#dashboard', as: 'dashboard_weight'
  resources :weight_data
  resources :outlets
  devise_for :users
  get 'screens/show/',to: 'screens#configInit'
  get 'screens/show/:id',to: 'screens#show'
  get 'screens/update',to:'screens#update'
  get 'screens/index', to:'screens#index'
  get  'screens/modal/:id', to:'screens#open_modal',as:'open_modal'
  get  'screens/modalb/:id', to:'screens#open_modal_back',as:'open_modalb'
  post 'screens/modal/update',to:'screens#open_modal_update',as:'open_modal_update'
  post 'screens/modal/update',to:'screens#open_modalback_update',as:'open_modalback_update'
  get 'admin/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/weight_device.rb
class WeightDevice < ApplicationRecord
end

app/controllers/weight_devices_controller.rb
class WeightDevicesController < ApplicationController
  layout 'admin'
  before_action :set_weight_device, only: %i[ show edit update destroy ]

  # GET /weight_devices or /weight_devices.json
  def index
    @weight_devices = WeightDevice.all
    @outlets = Outlet.all
  end

  # GET /weight_devices/1 or /weight_devices/1.json
  def show
  end

  def dashboard
    @weight_devices = WeightDevice.all
    @outlets = Outlet.all
    @weight_data = WeightDatum.order('created_at DESC')
    @weight_data_1 = WeightDatum.all
  end
  # GET /weight_devices/new
  def new
    @weight_device = WeightDevice.new
  end

  # GET /weight_devices/1/edit
  def edit
  end

  # POST /weight_devices or /weight_devices.json
  def create
    @weight_device = WeightDevice.new(weight_device_params)

    respond_to do |format|
      if @weight_device.save
        format.html { redirect_to weight_device_url(@weight_device), notice: "Weight device was successfully created." }
        format.json { render :show, status: :created, location: @weight_device }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weight_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weight_devices/1 or /weight_devices/1.json
  def update
    respond_to do |format|
      if @weight_device.update(weight_device_params)
        format.html { redirect_to weight_device_url(@weight_device), notice: "Weight device was successfully updated." }
        format.json { respond_with_bip(@weight_device) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { respond_with_bip(@weight_device) }
      end
    end
  end

  # DELETE /weight_devices/1 or /weight_devices/1.json
  def destroy
    @weight_device.destroy

    respond_to do |format|
      format.html { redirect_to weight_devices_url, notice: "Weight device was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight_device
      @weight_device = WeightDevice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def weight_device_params
      params.require(:weight_device).permit(:id,:weight_device,:outlet_name)
    end
end

app/helpers/weight_devices_helper.rb
module WeightDevicesHelper
end

app/views/weight_devices/_form.html.erb
<%= form_with(model: weight_device) do |form| %>
  <% if weight_device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weight_device.errors.count, "error") %> prohibited this weight_device from being saved:</h2>

      <ul>
        <% weight_device.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/weight_devices/dashboard.html.erb
<div class="container mt-5">
  <div class="card text-center">
    <div class="p-1">
      <h3 class="p-1">Dispositivos </h3>
      <table class='table table-striped '>
        <thead>
          <tr>
            <th>Id</th>
            <th>Mac Address</th>
            <th>Ip Address</th>
            <th>Nombre Salidas</th>
            <th>Creado</th>
            <th>Estado</th>
          </tr>
        </thead>

        <tbody>
          <% @weight_devices.each do |weight_device| %>
          <tr>
            <td><%= weight_device.id_device %></td>
            <td><%= weight_device.mac_address %></td>
            <td><%= weight_device.ip_address %></td>
            <td><%= weight_device.outlet_name %></td>
            <td><%= weight_device.firmware %></td>
            <td><i id="heartbeat-<%= weight_device.id_device  %>" class='bx bxs-circle gray'></i>
            <td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row mt-2 text-left mb-2">
    <div class="col-6">
      <div class="card ultimo-peso">
        <h3 class="text-center pt-5">Ultimo peso</h3>
        <div class="row">
          <div class="col-6 text-center pt-5"><span id="weight">Null</span><span class="unit">&nbsp;Kg</span></div>
          <div class="col-6">
            <div class="pt-4"><span>Nombre Salida:&nbsp;</span><span   class="fw-bold" id="outletName">Null</span></div>
            <div class="pt-4"><span>Nombre Producto:&nbsp;</span><span class="fw-bold" id="outletProduct">Null</span></div>
            <div class="pt-4"><span>Nombre Empaque:&nbsp;</span><span  class="fw-bold" id="outletpacket">Null</span></div>
            <div class="pt-4"><span>Peso Empaque:&nbsp;</span><span    class="fw-bold" id="outletweight">Null</span></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-6">
      <div class="card "></div>
      <h3 class="text-center pt-5"> Mediciones Dispositivos</h3>
      <div class="">
        <%= scatter_chart WeightDatum.group(:outlet_name,:weight).count, xtitle: "Weight", ytitle: "Salida",height: "200px",decimal: ","%>
      </div>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-8">
      <div class="card text-center">
        <div class="p-1">
          <h3 class="p-1">Salidas</h3>
          <table class='table table-striped'>
            <thead>
              <tr>
                <th>Nombre Salidas</th>
                <th>Nombre Producto</th>
                <th>Nombre Paquete</th>
                <th>Peso Paquete</th>
                <th>Estado Salida</th>
              </tr>
            </thead>

            <tbody>
              <% @outlets.each do |outlet| %>
              <tr>
                <td>
                  <%= outlet.outlet_name %>
                </td>
                <td>
                  <%= outlet.product_name %>
                </td>
                <td>
                  <%= outlet.pack_name %>
                </td>
                <td>
                  <%= outlet.pack_weight_kg %>
                </td>
                <td>
                  <%= outlet.outlet_status %>
                </td>
                <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card text-center">
        <div class="p-1">
          <h3 class="p-1">Pesos</h3>
          <table class='table table-striped table-wrapper'>
            <thead>
              <tr>
                <th>N°</th>
                <th>Dispositivo</th>
                <th>Salida</th>
                <th>Peso</th>
                <th>Unidad</th>
                <th>creado</th>

              </tr>
            </thead>

            <tbody>
              <% @weight_data.each do |weight_datum| %>
              <tr>
                <td>
                  <%= weight_datum.id_weight_data %>
                </td>
                <td>
                  <%= weight_datum.id_device %>
                </td>
                <td>
                  <%= weight_datum.outlet_name %>
                </td>
                <td>
                  <%= ((weight_datum.weight.to_f/1000).round(3).to_s) %>
                </td>
                <% if weight_datum.unit=='0' %>
                <td>kg</td>
                <% else %>
                <td>lb</td>
                <% end %>
                <td>
                  <%= time_ago_in_words(weight_datum.created_at) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-2 mb-2">
    <div class="col-6">
      <div class="card text-center ">
        <div class="p-1">
          <h3 class="p-1">Distribución Pesos </h3>
        </div>
        <%= pie_chart @weight_data_1.group(:weight).count %>
      </div>
    </div>
    <div class="col-6">
      <div class="card text-center ">
        <div class="p-1">
          <h3 class="p-1">Promedio de Pesos por salida </h3>
        </div>
        <%= bar_chart @weight_data_1.group(:outlet_name).average(:weight) %>
      </div>
    </div>
  </div>

</div>

app/views/weight_devices/edit.html.erb
<h1>Editing Weight Device</h1>

<%= render 'form', weight_device: @weight_device %>

<%= link_to 'Show', @weight_device %> |
<%= link_to 'Back', weight_devices_path %>

app/views/weight_devices/index.html.erb
<div class="container mt-5 text-center">  
  <h3>Dispositivos de pesos</h1>
  
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Id</th>
        <th>Mac Address</th>
        <th>Ip Address</th>
        <th>Nombre Salidas</th>
        <th>Firmware</th>
        <th>Creado</th>
        
      </tr>
    </thead>
  
    <tbody>
      <% @weight_devices.each do |weight_device| %>
        <tr>
        <td><%= weight_device.id_device %></td>
        <td><%= weight_device.mac_address %></td>
        <td><%= weight_device.ip_address %></td>
        <td><%= best_in_place weight_device, :outlet_name , :as=> :select, collection: Outlet.all.map {|outlet|
                [outlet.outlet_name,"#{outlet.outlet_name}"]} ,tabindex: "1" %></td>
        <td><%= weight_device.firmware %></td>
        <td><%= time_ago_in_words(weight_device.created_at) %></td>
        
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <h3>Salidas calibrador</h3>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Nombre Salidas</th>
        <th>Nombre Producto</th>
        <th>Nombre Paquete</th>
        <th>Peso Paquete</th>
        <th>Estado Salida</th>
      </tr>
    </thead>
  
    <tbody>
      <% @outlets.each do |outlet| %>
        <tr>
        <td><%= outlet.outlet_name %></td>
        <td><%= outlet.product_name %></td>
        <td><%= outlet.pack_name %></td>
        <td><%= outlet.pack_weight_kg %></td>
        <td><%= outlet.outlet_status %></td>
      <% end %>
    </tbody>
    </table>
</div>

app/views/weight_devices/new.html.erb
<h1>New Weight Device</h1>

<%= render 'form', weight_device: @weight_device %>

<%= link_to 'Back', weight_devices_path %>

app/views/weight_devices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_weight_device_path(@weight_device) %> |
<%= link_to 'Back', weight_devices_path %>